version: "3.7"

# Will use the hostname when talking between services on the same network
services:
  
  member-ui:
    build: .
    # Build the image with name and tag
    image: member-ui:1.0
    hostname: member-ui
    container_name: member-ui
    # Map post 5000 on host machine to 80 on container
    ports:
      - "5000:80"
    networks:
      - hubmap
    volumes:
      # Make the uwsgi logging generated on container available through from host
      - "./log:/usr/src/app/log"
       # Mount the source code to container
      - "../member-ui:/usr/src/app/src"
      # Mount conf.d-dev to the nginx conf.d on container
      - "./nginx/conf.d:/etc/nginx/conf.d"
  
  # Only used by local development
  member-mysql:
    build: ./member-mysql
    # Build the image with name and tag
    image: member-mysql:1.0
    hostname: member-mysql
    container_name: member-mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123
    # Use the same port mapping for dev and prod
    ports:
      - "3306:3306"
    networks:
      - hubmap


networks:
  hubmap: